trigger:
  - main

pool:
  vmImage: ubuntu-latest
steps:
  - task: NodeTaskRunnerInstaller@0
    inputs:
      nodeVersion: '16'
  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'compile'
      publishJUnitResults: false
      #testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.17'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false
  - script: |
      npx playwright install
    displayName: 'Install Playwright Browsers'
  - script: |
      mvn clean test
    displayName: 'Run Playwright Tests'
  - task: PublishHtmlReport@1
    displayName: 'Generate HTML Report'
    inputs:
      reportDir: 'reports/index.html'
  - powershell: |
      $EmailFrom = "$(GMAIL_USERNAME)"
      $EmailTo = "niyazhashmi161921@gmail.com"
      $Subject = "HTML Report from Azure Pipeline"
      $Body = "Please find the attached HTML test report."
      $SMTPServer = "smtp.gmail.com"
      $SMTPPort = "587"
      $Username = "$(GMAIL_USERNAME)"
      $Password = "$(GMAIL_APP_PASSWORD)"
      $htmlContent = Get-Content -Path "$(System.DefaultWorkingDirectory)/reports/summaryReport.html" -Raw
      $message = New-Object system.net.mail.mailmessage
      $message.from = $EmailFrom
      $message.To.add($EmailTo)
      $message.Subject = $Subject
      $message.Body = $Body
      $message.Attachments.Add($Attachment)
      
      $smtp = New-Object Net.Mail.SmtpClient($SMTPServer, $SMTPPort)
      $smtp.EnableSsl = $true
      $smtp.Credentials = New-Object System.Net.NetworkCredential($Username, $Password)
      $smtp.Send($message)
    displayName: 'Emailing HTML Report...'
continueOnError: true
