
# docker-compose up -d
# SELENIUM_REMOTE_URL=http://localhost:4444 mvn test
#  docker-compose down

#version: "3"
services:
  chrome:
    image: selenium/node-chrome:beta
    shm_size: 2gb
    platform: linux/amd64
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_MAX_OVERRIDE_SESSIONS=true
      - SE_NODE_GRID_URL=http://localhost:4444/

  edge:
    image: selenium/node-edge:beta
    shm_size: 2gb
    platform: linux/amd64
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_MAX_OVERRIDE_SESSIONS=true
      - SE_NODE_GRID_URL=http://localhost:4444/

  firefox:
    image: selenium/node-firefox:beta
    shm_size: 2gb
    platform: linux/amd64
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_MAX_OVERRIDE_SESSIONS=true
      - SE_NODE_GRID_URL=http://localhost:4444/

  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    platform: linux/amd64
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"