version: '3'
services:
  selenium-hub:
    image: selenium/hub:4.1.0
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.1.0
    environment:
      - HUB_HOST=selenium-hub
    depends_on:
      - selenium-hub
