name: Playwright Java Tests
on:
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build & Install
        run: mvn -B install -D skipTests --no-transfer-progress
      - name: Ensure browsers are installed
        run: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install --with-deps"
      - name: Run tests
        run: mvn clean test -Pbrowserstack -Denv=browserstack
      - name: Upload Extent Report
        uses: actions/upload-artifact@v4
        with:
          if: always()
          name: html-report
          path: reports/index.html
          retention-days: 1
      - name: Send email with HTML report
        uses: dawidd6/action-send-mail@v3
        with:
            if: always()
            server_address: smtp.gmail.com
            server_port: 465
            username: ${{ secrets.EMAIL_USERNAME }}
            password: ${{ secrets.EMAIL_PASSWORD }}
            subject: "Test Results for Build #${{ github.run_number }} - ${{ github.repository }}"
            html_body: file://reports/summaryReport.html
            to: niyazhashmi161921@gmail.com
            from: niyazhashmi161921@gmail.com
            attachments: reports/index.html
            secure: true
      - name: Upload HTML Report to AWS S3 and trigger Email through Lambda channel
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
            aws s3 cp --recursive ./reports s3://plawright-java-test-results